### ISSUE TITLE
Zona horaria del servidor

### ISSUE THREAD

**Issue by agubelu** [AgoraUS-G1-1617/continuous-integration-agoraus_g1#13]
Hola, he pensado que no sería una buena forma de acabar este 2016 sin poner alguna issue en EGC, así que ahí va:

Según hemos estado hablando en AgoraUS-G1-1617/Recuento-y-modificacion#17, parece ser que el servidor tiene una hora atrasada respecto al huso horario español, lo que provoca que las votaciones cierren una hora más tarde respecto a lo que se indica en las mismas si tomamos como referencia la zona horaria de los usuarios. Dado que no se puede determinar automáticamente la zona horaria basándose únicamente en una petición HTTP y guardar la de cada usuario sería un gran trabajo que requeriría de cambios en muchos subsistemas, creo que lo más razonable es simplemente cambiar la configuración del servidor de integración continua para que su hora sea la misma que la nuestra.

Un saludo.

**Comment by ManuelLR** [comment]
A pesar de todo lo comentado, la zona horaria del servidor está correctamente el problema es que cada contenedor no usa la zona horaria del host. La solución es configurar dicha zona horaria al lanzar el contenedor. 

Para los contenedores basados en la imagen "alpine" se deberá ejecutar el siguiente comando en el script:

```bash
docker exec $ENV_NAME-$BRANCH-nodejs apk add tzdata && \
docker exec $ENV_NAME-$BRANCH-nodejs cp /usr/share/zoneinfo/Europe/Madrid /etc/localtime
```

Para los basados en debian/ubuntu (y posiblemente otras distribuciones) se deberá ejecutar el siguiente comando en el script:
```bash
docker exec $ENV_NAME-$BRANCH-tomcat \
    bash -c "echo "Europe/Madrid" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata"
```

Podéis encontrar un ejemplo aquí: @877f2df5a93eacc72759f43eca8479dc6cd61601 @370f0a7


Por favor, todos los del equipo de @AgoraUS-G1-1617/integrators tenedlo en cuenta si necesitáis cualquier cosa relativa a la hora

**Comment by agubelu** [comment]
De acuerdo, pues le paso la tarea a @Dionakra que es el que se encarga de eso en nuestro grupo. Gracias.

**Comment by ManuelLR** [comment]
@agubelu reabro el issue puesto que el error no se ha solucionado todavía solo se ha explicado como debe solucionarlo cada uno en sus respectivos script

**Comment by Dionakra** [comment]
Buenas.

Se probó ayer con la nueva imagen y configuración de la imagen de Docker y los equipos han confirmado.

Cierro la issue al estar arreglado.
